author = "Gökmen Görgen"
baseurl = "/"
canonifyurls = true
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 5
theme = "alageek"
title = "alaGeek Theme"

[params]
copyright = "© 2018 by Gökmen Görgen"
copyrightUrl = "https://gokmengorgen.net"
description = "Hugo alaGeek Theme"
faviconfile = "https://gokmengorgen.net/img/laughing-man-favicon.png"
latestpostcount = 5
logofile = "https://gokmengorgen.net/img/laughing-man.png"
highlightjs = true
highlightjslanguages = [ "bash", "css", "diff", "django", "javascript", "python", "yaml" ]
toc = true
posts_navigation = true
progressively = true
flattr = "?"
github = "?"
gitlab = "?"
linkedin = "?"
telegram = "?"
twitter = "?"
mastodon_url = "https://mastodon.url/?"
email = "?@localhost"

[[params.best_posts]]
title = "Migrate to Hugo from Jekyll"
url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.secondary]]
identifier = "patreon"
name = "Become a patron"
url = "https://www.patreon.com/bePatron?u=10637849"
weight = 110

[[menu.secondary]]
identifier = "bmc"
name = "Buy me a coffee"
url = "https://www.buymeacoffee.com/gokmen"
weight = 120

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
